package com.aetherti.legaldelivery.gr.antalakas.android.LegalDelivery.Message;
// Generated by proto2javame, Wed Nov 21 12:25:56 IST 2012.

import java.io.IOException;
import java.io.InputStream;
import java.util.*;

import com.aetherti.legaldelivery.gr.antalakas.android.LegalDelivery.Message.RelatedPersonMessage.Builder;
import net.jarlehansen.protobuf.javame.UninitializedMessageException;
import net.jarlehansen.protobuf.javame.input.InputReader;
import net.jarlehansen.protobuf.javame.input.DelimitedInputStream;
import net.jarlehansen.protobuf.javame.input.DelimitedSizeUtil;
import net.jarlehansen.protobuf.javame.ComputeSizeUtil;
import net.jarlehansen.protobuf.javame.output.OutputWriter;
import net.jarlehansen.protobuf.javame.AbstractOutputWriter;
import net.jarlehansen.protobuf.javame.input.taghandler.UnknownTagHandler;
import net.jarlehansen.protobuf.javame.input.taghandler.DefaultUnknownTagHandlerImpl;

public final class RelatedPersonMessages extends AbstractOutputWriter {
	private static UnknownTagHandler unknownTagHandler = DefaultUnknownTagHandlerImpl.newInstance();

	private final java.util.Vector relatedPersonMessage;
	private static final int fieldNumberRelatedPersonMessage = 1;


	public static Builder newBuilder() {
		return new Builder();
	}

	@SuppressWarnings("unused")
	private RelatedPersonMessages(final Builder builder) {
		if (true) {
			this.relatedPersonMessage = builder.relatedPersonMessage;
		} else {
			throw new UninitializedMessageException("Not all required fields were included (false = not included in message), " + 
				"");
		}
	}

	public static class Builder {
		@SuppressWarnings("rawtypes")
		private java.util.Vector relatedPersonMessage = new java.util.Vector();
		private boolean hasRelatedPersonMessage = false;


		private Builder() {
		}

		public Builder setRelatedPersonMessage(final java.util.Vector relatedPersonMessage) {
			if(!hasRelatedPersonMessage) {
				hasRelatedPersonMessage = true;
			}
			this.relatedPersonMessage = relatedPersonMessage;
			return this;
		}


		public Builder addElementRelatedPersonMessage(final RelatedPersonMessage element) {
			if(!hasRelatedPersonMessage) {
				hasRelatedPersonMessage = true;
			}
			relatedPersonMessage.addElement(element);
			return this;
		}

		public RelatedPersonMessages build() {
			return new RelatedPersonMessages(this);
		}
	}

	@SuppressWarnings("rawtypes")
	public java.util.Vector getRelatedPersonMessage() {
		return relatedPersonMessage;
	}

	public String toString() {
		final String TAB = "   ";
		String retValue = "";
		retValue += this.getClass().getName() + "(";
		retValue += "relatedPersonMessage = " + this.relatedPersonMessage + TAB;
		retValue += ")";

		return retValue;
	}

	// Override
	public int computeSize() {
		int totalSize = 0;
		totalSize += computeNestedMessageSize();

		return totalSize;
	}

	private int computeNestedMessageSize() {
		int messageSize = 0;
		messageSize += ComputeSizeUtil.computeListSize(fieldNumberRelatedPersonMessage, net.jarlehansen.protobuf.javame.SupportedDataTypes.DATA_TYPE_CUSTOM, relatedPersonMessage);

		return messageSize;
	}

	// Override
	public void writeFields(final OutputWriter writer) throws IOException {
		writer.writeList(fieldNumberRelatedPersonMessage, net.jarlehansen.protobuf.javame.SupportedDataTypes.DATA_TYPE_CUSTOM, relatedPersonMessage);
		writer.writeData();
	}

	static RelatedPersonMessages parseFields(final InputReader reader) throws IOException {
		int nextFieldNumber = getNextFieldNumber(reader);
		final RelatedPersonMessages.Builder builder = RelatedPersonMessages.newBuilder();

		while (nextFieldNumber > 0) {
			if(!populateBuilderWithField(reader, builder, nextFieldNumber)) {
				reader.getPreviousTagDataTypeAndReadContent();
			}
			nextFieldNumber = getNextFieldNumber(reader);
		}

		return builder.build();
	}

	static int getNextFieldNumber(final InputReader reader) throws IOException {
		return reader.getNextFieldNumber();
	}

	static boolean populateBuilderWithField(final InputReader reader, final Builder builder, final int fieldNumber) throws IOException {
		boolean fieldFound = true;
		switch (fieldNumber) {
			case fieldNumberRelatedPersonMessage:
				Vector vcRelatedPersonMessage = reader.readMessages(fieldNumberRelatedPersonMessage);
				for(int i = 0 ; i < vcRelatedPersonMessage.size(); i++) {
					byte[] eachBinData = (byte[]) vcRelatedPersonMessage.elementAt(i);
					RelatedPersonMessage.Builder builderRelatedPersonMessage = RelatedPersonMessage.newBuilder();
					InputReader innerInputReader = new InputReader(eachBinData, unknownTagHandler);
					boolean boolRelatedPersonMessage = true;
					int nestedFieldRelatedPersonMessage = -1;
					while(boolRelatedPersonMessage) {
						nestedFieldRelatedPersonMessage = getNextFieldNumber(innerInputReader);
						boolRelatedPersonMessage = RelatedPersonMessage.populateBuilderWithField(innerInputReader, builderRelatedPersonMessage, nestedFieldRelatedPersonMessage);
					}
					eachBinData = null;
					innerInputReader = null;
					builder.addElementRelatedPersonMessage(builderRelatedPersonMessage.build());
				}
				break;
		default:
			fieldFound = false;
		}
		return fieldFound;
	}

	public static void setUnknownTagHandler(final UnknownTagHandler unknownTagHandler) {
		RelatedPersonMessages.unknownTagHandler = unknownTagHandler;
	}

	public static RelatedPersonMessages parseFrom(final byte[] data) throws IOException {
		return parseFields(new InputReader(data, unknownTagHandler));
	}

	public static RelatedPersonMessages parseFrom(final InputStream inputStream) throws IOException {
		return parseFields(new InputReader(inputStream, unknownTagHandler));
	}

	public static RelatedPersonMessages parseDelimitedFrom(final InputStream inputStream) throws IOException {
		final int limit = DelimitedSizeUtil.readDelimitedSize(inputStream);
		return parseFields(new InputReader(new DelimitedInputStream(inputStream, limit), unknownTagHandler));
	}
}