package com.aetherti.legaldelivery.gr.antalakas.android.LegalDelivery.Message;
// Generated by proto2javame, Wed Nov 21 12:25:56 IST 2012.

import java.io.IOException;
import java.io.InputStream;

import net.jarlehansen.protobuf.javame.AbstractOutputWriter;
import net.jarlehansen.protobuf.javame.ComputeSizeUtil;
import net.jarlehansen.protobuf.javame.UninitializedMessageException;
import net.jarlehansen.protobuf.javame.input.DelimitedInputStream;
import net.jarlehansen.protobuf.javame.input.DelimitedSizeUtil;
import net.jarlehansen.protobuf.javame.input.InputReader;
import net.jarlehansen.protobuf.javame.input.taghandler.DefaultUnknownTagHandlerImpl;
import net.jarlehansen.protobuf.javame.input.taghandler.UnknownTagHandler;
import net.jarlehansen.protobuf.javame.output.OutputWriter;

public final class RelatedBusinessMessage extends AbstractOutputWriter {
	private static UnknownTagHandler unknownTagHandler = DefaultUnknownTagHandlerImpl.newInstance();

	private final String RelatedBusinessID;
	private static final int fieldNumberRelatedBusinessID = 1;

	private final String LegalDeliveryID;
	private static final int fieldNumberLegalDeliveryID = 2;

	private final String Businessname;
	private static final int fieldNumberBusinessname = 3;


	public static Builder newBuilder() {
		return new Builder();
	}

	private RelatedBusinessMessage(final Builder builder) {
		if (builder.hasRelatedBusinessID && builder.hasLegalDeliveryID && builder.hasBusinessname ) {
			this.RelatedBusinessID = builder.RelatedBusinessID;
			this.LegalDeliveryID = builder.LegalDeliveryID;
			this.Businessname = builder.Businessname;
		} else {
			throw new UninitializedMessageException("Not all required fields were included (false = not included in message), " + 
				" RelatedBusinessID:" + builder.hasRelatedBusinessID + " LegalDeliveryID:" + builder.hasLegalDeliveryID + " Businessname:" + builder.hasBusinessname + "");
		}
	}

	public static class Builder {
		private String RelatedBusinessID;
		private boolean hasRelatedBusinessID = false;

		private String LegalDeliveryID;
		private boolean hasLegalDeliveryID = false;

		private String Businessname;
		private boolean hasBusinessname = false;


		private Builder() {
		}

		public Builder setRelatedBusinessID(final String RelatedBusinessID) {
			this.RelatedBusinessID = RelatedBusinessID;
			this.hasRelatedBusinessID = true;
			return this;
		}

		public Builder setLegalDeliveryID(final String LegalDeliveryID) {
			this.LegalDeliveryID = LegalDeliveryID;
			this.hasLegalDeliveryID = true;
			return this;
		}

		public Builder setBusinessname(final String Businessname) {
			this.Businessname = Businessname;
			this.hasBusinessname = true;
			return this;
		}

		public RelatedBusinessMessage build() {
			return new RelatedBusinessMessage(this);
		}
	}

	public String getRelatedBusinessID() {
		return RelatedBusinessID;
	}

	public String getLegalDeliveryID() {
		return LegalDeliveryID;
	}

	public String getBusinessname() {
		return Businessname;
	}

	public String toString() {
		final String TAB = "   ";
		String retValue = "";
		retValue += this.getClass().getName() + "(";
		retValue += "RelatedBusinessID = " + this.RelatedBusinessID + TAB;
		retValue += "LegalDeliveryID = " + this.LegalDeliveryID + TAB;
		retValue += "Businessname = " + this.Businessname + TAB;
		retValue += ")";

		return retValue;
	}

	// Override
	public int computeSize() {
		int totalSize = 0;
		totalSize += ComputeSizeUtil.computeStringSize(fieldNumberRelatedBusinessID, RelatedBusinessID);
		totalSize += ComputeSizeUtil.computeStringSize(fieldNumberLegalDeliveryID, LegalDeliveryID);
		totalSize += ComputeSizeUtil.computeStringSize(fieldNumberBusinessname, Businessname);
		totalSize += computeNestedMessageSize();

		return totalSize;
	}

	private int computeNestedMessageSize() {
		int messageSize = 0;

		return messageSize;
	}

	// Override
	public void writeFields(final OutputWriter writer) throws IOException {
		writer.writeString(fieldNumberRelatedBusinessID, RelatedBusinessID);
		writer.writeString(fieldNumberLegalDeliveryID, LegalDeliveryID);
		writer.writeString(fieldNumberBusinessname, Businessname);
		writer.writeData();
	}

	static RelatedBusinessMessage parseFields(final InputReader reader) throws IOException {
		int nextFieldNumber = getNextFieldNumber(reader);
		final RelatedBusinessMessage.Builder builder = RelatedBusinessMessage.newBuilder();

		while (nextFieldNumber > 0) {
			if(!populateBuilderWithField(reader, builder, nextFieldNumber)) {
				reader.getPreviousTagDataTypeAndReadContent();
			}
			nextFieldNumber = getNextFieldNumber(reader);
		}

		return builder.build();
	}

	static int getNextFieldNumber(final InputReader reader) throws IOException {
		return reader.getNextFieldNumber();
	}

	static boolean populateBuilderWithField(final InputReader reader, final Builder builder, final int fieldNumber) throws IOException {
		boolean fieldFound = true;
		switch (fieldNumber) {
			case fieldNumberRelatedBusinessID:
				builder.setRelatedBusinessID(reader.readString(fieldNumber));
				break;
			case fieldNumberLegalDeliveryID:
				builder.setLegalDeliveryID(reader.readString(fieldNumber));
				break;
			case fieldNumberBusinessname:
				builder.setBusinessname(reader.readString(fieldNumber));
				break;
		default:
			fieldFound = false;
		}
		return fieldFound;
	}

	public static void setUnknownTagHandler(final UnknownTagHandler unknownTagHandler) {
		RelatedBusinessMessage.unknownTagHandler = unknownTagHandler;
	}

	public static RelatedBusinessMessage parseFrom(final byte[] data) throws IOException {
		return parseFields(new InputReader(data, unknownTagHandler));
	}

	public static RelatedBusinessMessage parseFrom(final InputStream inputStream) throws IOException {
		return parseFields(new InputReader(inputStream, unknownTagHandler));
	}

	public static RelatedBusinessMessage parseDelimitedFrom(final InputStream inputStream) throws IOException {
		final int limit = DelimitedSizeUtil.readDelimitedSize(inputStream);
		return parseFields(new InputReader(new DelimitedInputStream(inputStream, limit), unknownTagHandler));
	}
}